name: Processing with Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        processing:
          - tag: "processing-1292-4.2"
            semver: "1292.0.0"
          - tag: "processing-1272-4.0a3"
            semver: "1272.0.0"
          - tag: "processing-0270-3.5.4"
            semver: "270.0.0"
          - tag: "processing-0232-3.0a5"
            semver: "232.0.0"
          - tag: "processing-0227-2.2.1"
            semver: "227.0.0"
    steps:
    
    -name: Checkout repository
      -uses: actions/checkout@v2
    id: setup-processing
    uses: pr1metine/setup-processing@v2.2.0
    with:
    # Tag of Processing GitHub Release, e.g. processing-1292-4.2
    # See https://github.com/processing/processing4/releases and
    # https://github.com/processing/processing4/releases
    tag: "processing-1292-4.2" # optional, will use latest release by default
    # Name of a Processing GitHub Release Asset, e.g. processing-4.2-linux-arm64.tgz
    asset-name: "processing-4.2-linux-x64.tgz" # optional, will infer based on Runner by default
    - name: Output Processing installation directory
  run: echo "${{steps.setup-processing.outputs.install-dir}}"
